---
- name: Run local command
  hosts: localhost
  connection: local
  vars:
    kube_version: v1.25.6
    calico_pool_blocksize: 24
    crio_packages: 1.25
  tasks:
    - name: Clone kubespray repository
      git:
        repo: https://github.com/kubernetes-sigs/kubespray.git
        dest: /tmp/kubespray
        version: v2.21.0

    - name: Run kubespray playbook
      command: ansible-playbook -i /tmp/kubespray/inventory/inventory.ini /tmp/kubespray/cluster.yml -e kube_version={{ kube_version }} --become -e calico_pool_blocksize={{ calico_pool_blocksize }} -e crio_packages={{ crio_packages }}